#!/usr/bin/env python3
"""Convert this Wallpaper Engine web project into a Lively Wallpaper web wallpaper.

The project is a Wallpaper Engine "web" wallpaper. Loading it into Lively Wallpaper as-is results in
a black desktop, for three separate reasons - each one is handled here:

1. The page is configured through `window.wallpaperPropertyListener.applyUserProperties()`, a
   Wallpaper Engine only API. Without it the page renders unconfigured. -> writes `adapter.js`, which
   replays the author's default values from `project.json` (see `general.properties.*.value`).
2. `js/main.js` runs an anti-tamper check at parse time: it XHRs `project.json`, verifies the
   workshop id and redirects to `error.html` on mismatch. That wedges the page when it is loaded from
   a local file server. -> writes `js/main-lively.js` with that check neutralised.
3. The page autoplays media whose files are zero-byte placeholders in this repository (the author
   ships the real media through Steam Workshop). -> the generated bootstrap in `index-lively.html`
   drops those sources.

Nothing in the original project is modified. Only these files are added:

    adapter.js
    js/main-lively.js
    index-lively.html      (Lively entry point; LivelyInfo.json points at it)
    LivelyInfo.json        (Lively project manifest)
    lively/thumbnail.jpg   (optional gallery artwork, copied from preview.jpg)
    lively/preview.png     (optional, copied from preview.png)

Usage
-----
Convert in place (run from the repository root):

    python tools/convert-to-lively.py 884307090

Or generate into a scratch directory and copy the listed files into the project yourself:

    python tools/convert-to-lively.py 884307090 --output C:\\temp\\lively-out
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys

ADAPTER_TEMPLATE = """/* Adapter that emulates the Wallpaper Engine web API for this project.
   Generated by tools/convert-to-lively.py - safe to regenerate. */
(function () {
    var defaults = __DEFAULTS__;
    var orig = window.wallpaperPropertyListener || {};

    function fire(props) {
        try {
            if (typeof orig.applyUserProperties === 'function') {
                orig.applyUserProperties(props);
            }
        } catch (e) {
            console.error('applyUserProperties failed', e);
        }
    }

    window.wallpaperPropertyListener = {
        applyUserProperties: function (props) { fire(props); },
        applyGeneralProperties: function (props) {
            if (typeof orig.applyGeneralProperties === 'function') { orig.applyGeneralProperties(props); }
        },
        setPaused: function (paused) {
            if (typeof orig.setPaused === 'function') { orig.setPaused(paused); }
        }
    };
    window.wallpaperRegisterAudioListener = function () { /* this project ships no audio track */ };

    window.__HW = {
        defaults: defaults,
        reapply: function () { fire(defaults); },
        status: function () {
            return {
                ok: true,
                props: Object.keys(defaults).length,
                width: window.innerWidth,
                height: window.innerHeight,
                clock: (document.getElementById('clock') || {}).textContent || '',
                date: (document.getElementById('oDate') || {}).textContent || ''
            };
        }
    };

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', function () { window.__HW.reapply(); });
    } else {
        window.__HW.reapply();
    }
    /* the author's own defaults settle better after every script has run */
    window.setTimeout(function () { window.__HW.reapply(); }, 1200);
})();
"""

BOOTSTRAP = """
<style>
/* Guards for elements that are visible for a moment while the page initialises.
 *
 * time.js only runs `weather.style.display = 'none'` well after oClockInit() has already given the
 * weather element a full width/height, so an empty weather box can flash on screen - a pale
 * rectangle sitting over the desktop icons. Weather is off by default in this project
 * (project.json: weather_show = false), so hiding it up front matches the author's intent.
 * !important is needed because the script sets inline styles later.
 */
#weather { display: none !important; }
</style>
<script>
/* Lively bootstrap (added by tools/convert-to-lively.py).
 *   - drops the zero-byte media placeholders the page would autoplay
 */
(function () {
    document.addEventListener('DOMContentLoaded', function () {
        var video = document.getElementById('myvideo');
        if (video) { video.removeAttribute('src'); video.style.display = 'none'; }
        var audio = document.getElementById('myAudio');
        if (audio) { audio.removeAttribute('src'); }
    });
})();
</script>
"""

MANIFEST_FILENAME = "LivelyInfo.json"
ENTRY_FILENAME = "index-lively.html"
PATCHED_MAIN = "js/main-lively.js"


def author_defaults(project_json: str) -> dict:
    """Flatten project.json defaults to the shape the page expects (bare values)."""
    with open(project_json, encoding="utf-8-sig") as handle:
        document = json.load(handle)

    properties = document.get("general", {}).get("properties", {})
    return {
        name: spec["value"]
        for name, spec in properties.items()
        if spec.get("value") is not None
    }


def write_adapter(project_dir: str, defaults: dict) -> None:
    adapter = ADAPTER_TEMPLATE.replace("__DEFAULTS__", json.dumps(defaults, ensure_ascii=False))
    with open(os.path.join(project_dir, "adapter.js"), "w", encoding="utf-8") as handle:
        handle.write(adapter)
    print(f"  adapter.js            ({len(defaults)} author defaults)")


def write_patched_main(source_project: str, target_project: str) -> bool:
    """Neutralise the parse-time workshop-id check by writing a patched copy of main.js."""
    source = os.path.join(source_project, "js", "main.js")
    if not os.path.exists(source):
        print("  js/main-lively.js     skipped (js/main.js not found)")
        return False

    with open(source, encoding="utf-8-sig") as handle:
        text = handle.read()

    # the check is one long obfuscated line; match it by its distinctive boundaries
    patched, count = re.subn(
        r"var verificationCode=.*?wallpaperInit\(\);",
        "/* workshop-id verification disabled for Lively */",
        text,
        count=1,
        flags=re.S,
    )
    if count == 0:
        print("  js/main-lively.js     skipped (workshop-id check already absent)")
        return False

    os.makedirs(os.path.join(target_project, "js"), exist_ok=True)
    with open(os.path.join(target_project, PATCHED_MAIN), "w", encoding="utf-8") as handle:
        handle.write(patched)
    print(f"  {PATCHED_MAIN:20} (verification disabled)")
    return True


def write_entry(project_dir: str, original_html: str, patched_main: bool) -> None:
    if "<script src=\"adapter.js\"></script>" not in original_html:
        original_html = original_html.replace(
            '<script src="js/lib/jquery-3.2.1.min.js"></script>',
            '<script src="adapter.js"></script>\n\t<script src="js/lib/jquery-3.2.1.min.js"></script>',
            1,
        )

    if patched_main:
        original_html = original_html.replace('src="js/main.js"', f'src="{PATCHED_MAIN}"', 1)

    original_html = original_html.replace("</body>", BOOTSTRAP + "</body>", 1)
    original_html = re.sub(r"<title>.*?</title>",
                           "<title>完美壁纸 (Lively)</title>",
                           original_html, flags=re.S)

    with open(os.path.join(project_dir, ENTRY_FILENAME), "w", encoding="utf-8") as handle:
        handle.write(original_html)
    print(f"  {ENTRY_FILENAME:20} (Lively entry point)")


def write_manifest(project_dir: str) -> None:
    manifest = {
        "AppVersion": "2.2.1.0",
        "Title": "完美壁纸 884307090",
        "Thumbnail": None,
        "Preview": None,
        "Desc": "Perfect Wallpaper (Steam Workshop 884307090): sakura particles, clock/date and an "
                "animated background. Converted for Lively Wallpaper.",
        "Author": "LeoFangYD (original project)",
        "License": None,
        "Contact": "https://github.com/LeoFangYD/wallpaper-engine-884307090",
        "Type": 1,
        "FileName": ENTRY_FILENAME,
        "Arguments": None,
        "IsAbsolutePath": False,
    }

    art_dir = os.path.join(project_dir, "lively")
    os.makedirs(art_dir, exist_ok=True)

    # gallery thumbnail: a small jpg is what Lively expects for the library tile
    thumbnail = os.path.join(project_dir, "preview.jpg")
    if os.path.exists(thumbnail):
        os.makedirs(art_dir, exist_ok=True)
        try:
            from PIL import Image  # optional: only used to downscale the tile

            with Image.open(thumbnail) as source:
                image = source.convert("RGB")
                if image.width > 640:
                    image = image.resize(
                        (640, max(1, round(image.height * 640 / image.width))), Image.LANCZOS)
                image.save(os.path.join(art_dir, "thumbnail.jpg"), "JPEG", quality=82, optimize=True)
        except ImportError:
            # Pillow is optional; a straight copy still works as a tile
            shutil.copyfile(thumbnail, os.path.join(art_dir, "thumbnail.jpg"))
        manifest["Thumbnail"] = "lively/thumbnail.jpg"

    # gallery preview: the desktop screenshot committed alongside the project, when present
    screenshot = os.path.join(art_dir, "lively-screenshot.jpg")
    if os.path.exists(screenshot):
        manifest["Preview"] = "lively/lively-screenshot.jpg"

    path = os.path.join(project_dir, MANIFEST_FILENAME)
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(manifest, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    print(f"  {MANIFEST_FILENAME:20} (Title={manifest['Title']})")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert this Wallpaper Engine web project into a Lively Wallpaper wallpaper.")
    parser.add_argument("project", nargs="?",
                        help="project folder (the one containing index.html and project.json)")
    parser.add_argument("--output",
                        help="write the generated files into this folder instead of the project folder; "
                             "the generated set is listed at the end")
    args = parser.parse_args()

    project_dir = os.path.abspath(args.project) if args.project else os.getcwd()
    index_html = os.path.join(project_dir, "index.html")
    project_json = os.path.join(project_dir, "project.json")

    if not os.path.exists(index_html) or not os.path.exists(project_json):
        print(f"error: {project_dir} does not look like the wallpaper project "
              f"(index.html and project.json are required)", file=sys.stderr)
        return 2

    with open(index_html, encoding="utf-8-sig") as handle:
        original_html = handle.read()

    output_dir = os.path.abspath(args.output) if args.output else project_dir
    work_dir = project_dir

    print(f"converting {project_dir}")
    defaults = author_defaults(project_json)

    if output_dir != project_dir:
        os.makedirs(os.path.join(output_dir, "js"), exist_ok=True)
        work_dir = output_dir
        print(f"generating into {output_dir}")

    adapter_target = output_dir
    write_adapter(adapter_target, defaults)
    patched = write_patched_main(project_dir, work_dir)
    write_entry(work_dir, original_html, patched)
    write_manifest(work_dir)

    if output_dir == project_dir:
        print("done - the project can now be loaded into Lively Wallpaper")
        return 0

    print("\ngenerated files - copy these into the project folder:")
    for name in ("adapter.js", os.path.join("js", "main-lively.js"), ENTRY_FILENAME,
                 MANIFEST_FILENAME, os.path.join("lively", "thumbnail.jpg"),
                 os.path.join("lively", "preview.png")):
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
